version: "3.9"
   
services:
  app:
    build: .
    # image: coding_test:v1
    command: >   
        bash -c "cd /app/
        && python manage.py makemigrations
        && python manage.py migrate
        && gunicorn --bind 0.0.0.0:8000 core.wsgi"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  #   depends_on:
  #     - db
  # db:
  #   image: postgres:13
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: admindb
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #   ports:
  #   - "5432:5432"