# Generated by Django 3.2.8 on 2021-10-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Parent First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Parent Last Name')),
                ('street', models.CharField(max_length=100, verbose_name='Street Address')),
                ('city', models.CharField(max_length=100, verbose_name='City Name')),
                ('state', models.CharField(max_length=100, verbose_name='State Name')),
                ('zip_code', models.IntegerField(verbose_name='Zip Code')),
            ],
            options={
                'verbose_name_plural': 'Parent Data',
            },
        ),
        migrations.CreateModel(
            name='ChildUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Child First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Child Last Name')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parentuser')),
            ],
            options={
                'verbose_name_plural': 'Child Data',
            },
        ),
    ]
