# Generated by Django 3.2.8 on 2021-10-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childuser',
            old_name='first_name',
            new_name='child_first_name',
        ),
        migrations.RenameField(
            model_name='childuser',
            old_name='last_name',
            new_name='child_last_name',
        ),
    ]
