# Generated by Django 3.2.8 on 2021-10-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211018_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childuser',
            name='parent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.parentuser'),
        ),
    ]
