# Generated by Django 3.2.8 on 2021-10-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.author'),
        ),
    ]
