# Generated by Django 3.2.8 on 2021-10-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_childuser_parent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentuser',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Parent First Name'),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Parent Last Name'),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='state',
            field=models.CharField(max_length=100, null=True, verbose_name='State Name'),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='zip_code',
            field=models.IntegerField(null=True, verbose_name='Zip Code'),
        ),
    ]
