# Generated by Django 3.2.8 on 2021-10-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211018_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childuser',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.parentuser'),
        ),
    ]
